services:
  - type: web
    name: fastapi-app
    env: docker
    repo: https://github.com/okyunsu/project25-fast.git
    region: singapore
    plan: free
    branch: main
    dockerContext: .
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        value: postgresql://myuser:mypass@database:5432/mydb

